import 'dart:typed_data';

import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import 'complaint_service.dart';

/// Generates a clean A4 PDF of the complaint draft.
class RecoveryPdf {
  Future<Uint8List> generate(RecoveryDraft draft) async {
    final doc = pw.Document(
      title: draft.emailSubject,
      author: 'Digital Kavach',
    );

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(48),
        build: (context) => [
          pw.Header(
            level: 0,
            child: pw.Text(
              'Digital Kavach — Fraud Complaint',
              style: pw.TextStyle(
                fontSize: 18,
                fontWeight: pw.FontWeight.bold,
              ),
            ),
          ),
          pw.Paragraph(
            text:
            'Generated: ${draft.generatedAt.day}/${draft.generatedAt.month}/${draft.generatedAt.year} '
                '${draft.generatedAt.hour}:${draft.generatedAt.minute.toString().padLeft(2, '0')} | '
                'Source: ${draft.source == DraftSource.ai ? 'AI-assisted' : 'Template'}',
            style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey600),
          ),
          pw.Divider(),
          pw.SizedBox(height: 16),
          pw.Paragraph(
            text: draft.complaintEn,
            style: const pw.TextStyle(fontSize: 11, lineSpacing: 4),
          ),
          pw.SizedBox(height: 24),
          pw.Divider(),
          pw.Paragraph(
            text:
            'This document was generated by Digital Kavach for informational '
                'purposes. Please verify all details before submission. '
                'For legal advice, consult a qualified advocate.',
            style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey500),
          ),
        ],
      ),
    );

    return doc.save();
  }
}